app:
  version: "0.1.0"
  shutdown_timeout: "5s"
  port: "8080"

logger:
  level: "debug"
  json: false

database:
  driver: "postgres"
  dsn: "postgres://pt_user:pt_pass@localhost:5432/portfolio?sslmode=disable"
  max_open_conns: 10
  max_idle_conns: 5
  conn_max_lifetime: "30m"


jwt:
  secret: "super-secret"
  access_token_ttl: "15m"
  refresh_token_ttl: "720h"

coingecko:
  base_url: "https://api.coingecko.com/api/v3"
  request_timeout: "5s"

redis:
  enabled: false
